name: AUR

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: "manjarolinux/base"
      options: "--privileged=true --tmpfs /tmp --tmpfs /run"
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pacman -Sy --noconfirm --needed base-devel git sudo yay # man-pages man-db procps-ng

    - name: Create non root user
      run: |
          # Wheel group is the sudo group in Arch Linux
          useradd --create-home --groups wheel  user
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
          echo "PWD: $PWD"
          cat /etc/passwd

    - name: Build
      run: sudo -u user yay -Sy --noconfirm --needed --builddir . gdm-settings

#     - name: Build
#       run: |
#         package=blueprint-compiler-git
#         sudo -u user git clone https://aur.archlinux.org/$package.git
#         cd $package
#         sudo -u user makepkg --noconfirm -si
#         mv *.pkg.tar.zst ..

    - run: ls -lRh
      if: always()

