name: AUR

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    container: "manjarolinux/base"
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pacman -Sy --noconfirm --needed base-devel git pamac-cli sudo

    - name: List installed packages
      run: pamac list --installed

#     - name: Create non root user
#       run: |
#           # Wheel group is the sudo group in Arch Linux
#           useradd --create-home --groups wheel  user
#           echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
#           echo "PWD: $PWD"
#           cat /etc/passwd

    - name: Build
      run: |
        echo "" > /etc/pamac.conf
        echo "EnableAUR" > /etc/pamac.conf
        
        pamac build --keep --no-confirm --builddir . gdm-settings 
        ls -lRh
        
        sudo -u user git clone https://aur.archlinux.org/gdm-settings.git
        cd gdm-settings
        sudo -u user makepkg --noconfirm -s

    - run: cat /etc/makepkg.conf
      if: always()

    - run: cat /etc/pamac.conf
      if: always()

    - run: pamac build --help
      if: always()

    - run: ls -lRh
      if: always()
    
