name: AUR

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: "manjarolinux/base"
      options: "--privileged=true --tmpfs /tmp --tmpfs /run --entrypoint /sbin/init"
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pacman -Sy --noconfirm --needed base-devel git pamac-cli sudo yay man-pages man-db procps-ng

    - name: List installed packages
      run: pamac list --installed

    - name: Create non root user
      run: |
          # Wheel group is the sudo group in Arch Linux
          useradd --create-home --groups wheel  user
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
          echo "PWD: $PWD"
          cat /etc/passwd

#     - name: Build
#       continue-on-error: true
#       run: pamac build --no-confirm gdm-settings

    - name: Build
      continue-on-error: true
      run: yay -Sy --noconfirm --needed --builddir build --verbose --pacman $(which pacman) gdm-settings

    - name: Build
      continue-on-error: true
      run: sudo -u user yay -Sy --noconfirm --needed --builddir build --verbose gdm-settings

    - name: Build
      run: |
        package=blueprint-compiler-git
        sudo -u user git clone https://aur.archlinux.org/$package.git
        cd $package
        sudo -u user makepkg --noconfirm -si
        mv *.pkg.tar.zst ..
        
    - name: Build
      run: |
        package=gdm-settings
        sudo -u user git clone https://aur.archlinux.org/$package.git
        cd $package
        sudo -u user makepkg --noconfirm -si
        mv *.pkg.tar.zst ..
        
    - run: cat /etc/makepkg.conf
      if: always()

    - run: yay --help
      if: always()

    - run: man yay
      if: always()

    - run: ps aux
      if: always()
      
    - run: pamac build --help
      if: always()

    - run: ls -lRh
      if: always()

